name: Build

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build
    timeout-minutes: 10
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Test
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
